title: whatevenisapointer
author:
  name: whatevenisapointer
  email: WhatevenIsapointer@proton.me

description: RE and exploit dev notes

url: "https://whatevenisapointer.github.io"

minima:
  skin: dark

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
